version: '3.7'

services:
  # ELASTICSEARCH: 578 MB
  elasticsearch7:
    hostname: elasticsearch7
    container_name: elasticsearch7
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx1g 
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
#      - elasticsearchdata7:/usr/share/elasticsearch/data
      - ./etc_elasticsearch_elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
 
  # ELASTICVUE: 22 MB
  elasticvue3:
    hostname: elasticvue3
    container_name: elasticvue3
    image: cars10/elasticvue
    ports:
      - "9400:8080"
    depends_on: 
      - elasticsearch7
    # note: wait a moment before accessing http://localhost:9400 elasticsearch might took a time to start

#volumes:
#  elasticsearchdata7:





