# https://vectorized.io/docs/quick-start-docker/
version: '3.7'
services:
  redpanda1:
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "32"
      - --node-id
      - '0'
      - --set
      - redpanda.auto_create_topics_enabled=true
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    image: docker.vectorized.io/vectorized/redpanda:latest
    container_name: redpanda1
    ports:
      - 9092:9092
      - 29092:29092
    volumes:
      - ./redpanda1:/var/lib/redpanda
